services:
  api-wrapper-mcp:
    build: .
    container_name: api-wrapper-mcp
    environment:
      API_GATEWAY_TOKEN: "${API_GATEWAY_TOKEN}"
      RYBBIT_API_KEY: "${RYBBIT_API_KEY}"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-wrapper-mcp.rule=Host(`mcp.martin-linde.com`)"
      - "traefik.http.routers.api-wrapper-mcp.entrypoints=websecure"
      - "traefik.http.routers.api-wrapper-mcp.tls.certresolver=letsencrypt"
